server:
  port: 6000
  host: "0.0.0.0"
  mode: "debug" # "release" or "debug"

database:
  type: "mysql"
  source: "ginhub:ginhub@tcp(serv.horon.top:3306)/ginhub?parseTime=True&loc=Local"
  logmode: "release" # "release" or "debug"

auth:
  jwt:
    expires: 2592000 # 30天（单位秒）
    issuer: "ginhub"
    audience: "ginhub"
