server:
  port: "8080"
  host: "0.0.0.0"
  mode: "debug"

database:
  type: "mysql"
  source: "root:password@tcp(127.0.0.1:3306)/ginhub?charset=utf8mb4&parseTime=True&loc=Local"
  logmode: "debug"

auth:
  jwt:
    expires: 2592000
    issuer: "ginhub"
    audience: "ginhub"
